### ISSUE TITLE
Availability should respect policy filter

### ISSUE THREAD

**Issue by timdrysdale** [practable/book#15]
Currently, policy filters are respected on booking requests, but the availability provided to users is misleading because it does not depend on the policy filter. For example, availability is offered after the last `allowed` window

window spec
```
  w-pend-engdes1:
    allowed:
      - start: 2023-02-10T12:00:00Z
        end:   2023-02-10T17:00:00Z
      - start: 2023-02-11T12:00:00Z
        end:   2023-02-11T17:00:00Z
      - start: 2023-02-12T12:00:00Z
        end:   2023-02-12T17:00:00Z     
    denied: []
```
Gives this availability after the last allowed window reported at ca. 2023-02-15T16:54:18.213Z
```
[ { "end": "2023-02-16T18:35:46.999Z", "start": "2023-02-15T16:54:18.213Z" }, { "end": "2123-01-22T16:54:18.213Z", "start": "2023-02-16T18:40:47.000Z" } ]
```

The lack of dependence is confirmed by checking the code in `internal/store/store.go` for `getAvailability()` which just inverts the slots bookings list.

## Discussion
The use of separate AVL trees was originally conceived for speed in checking whether booking requests could be made. This overlooks that the most common action is requesting a list of times when a booking could be made in future (based on current bookings and policy settings).  

Slots cannot be shared between policies, but resources can. So we cannot pre-load a resource's diary with blocked out intervals corresponding to a filter for a slot, because multiple slots may use that resource and would typically do so at orthogonal times.
