### ISSUE TITLE
Manifest export not respecting YAML tags

### ISSUE THREAD

**Issue by timdrysdale** [practable/book#16]
The exported policy snippet below is missing the underscores between words, that are present in the original manifest. This would not be re-uploadable in its present form, so it should come back in the same format that it is uploaded in.
```
   p-everyone-trus:
    allowstartinpastwithin: 0s
    bookahead: 0s
    description: d-p-everyone-trus
    displayguides:
    - 5mFor20m
    - 15mFor1h
    enforceallowstartinpast: false
    enforcebookahead: false
    enforcegraceperiod: false
    enforcemaxbookings: false
    enforcemaxduration: false
    enforcemaxusage: false
    enforceminduration: false
    enforcenextavailable: false
    enforcestartswithin: false
    enforceunlimitedusers: false
    gracepenalty: 0s
    graceperiod: 0s
    maxbookings: 0
    maxduration: 0s
    maxusage: 0s
    minduration: 0s
    nextavailable: 0s
    slots:
    - sl-everyone-trus00
    - sl-everyone-trus01
    startswithin: 0s
```
